### ISSUE TITLE
Don't add a default tag

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-markdownit#2]
Hey, thanks for this, looks great!

Would you accept a PR that removes the default `div` tag? Ideally there should be no ambiguity in parsing, i.e. if the user didn't explicitly want that tag, then don't add it to the tree.

I did see the `tag` attribute, however that still forces you to wrap the markdown output in _some_ tag.

Also, considering this:

https://github.com/posthtml/posthtml-markdownit/blob/731dd47229d735f62f2a87359aa04e8e67843500/lib/index.js#L49-L54

if I use `tag: false` it'll still use a `div` around the compiled markdown.

Let me know, I can work on a PR later today 👍

**Comment by TheComputerM** [comment]
No problem, but make sure that if user specifies any attributes in the `md` tag, they are still rendered in the final markup.

**Comment by cossssmin** [comment]
Of course :)

Gave it a spin, works well. I think the boilerplate needs an update + the plugin needs minor cleanup here and there, there are a few lagacy things in it. Gonna rewrite it and open a PR 👍

**Comment by TheComputerM** [comment]
Thanks,
Man I really don't know how to name variables, do I? 😆

**Comment by cossssmin** [comment]
Don't worry about it! And please don't panic when you see the PR - I'm rewriting it so it uses a more up-to-date boilerplate and syntax, but your core functionality will not be changed 🙂
