### ISSUE TITLE
npm permissions

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-markdownit#8]
@TheComputerM Hello, could you share the rights to this critical publishing package?

**Comment by TheComputerM** [comment]
@Scrum You now have the role of `admin` as I have.

**Comment by Scrum** [comment]
> @Scrum You now have the role of `admin` as I have.

Thanks 👍

**Comment by Scrum** [comment]
@TheComputerM but still

```bash
403 403 Forbidden - PUT https://registry.npmjs.org/posthtml-markdownit - You do not have permission to publish "posthtml-markdownit". Are you logged in as the correct user?
```

maybe it takes a little time

**Comment by TheComputerM** [comment]
Is your name scrum on npm?

**Comment by Scrum** [comment]
@TheComputerM  did you send me an invite?

**Comment by TheComputerM** [comment]
Yeah, just did, was getting 404 errors before, don't know why.

**Comment by Scrum** [comment]
Wow, this is very strange. I will wait for an invite from you

**Comment by Scrum** [comment]
Could you, while I'm waiting for an invite, publish the master with version 1.2.2?

**Comment by TheComputerM** [comment]
![image](https://user-images.githubusercontent.com/24741538/97453588-e636c700-195b-11eb-9d17-0d760450df95.png)
This has been showing for the past 2 minutes

**Comment by Scrum** [comment]
> ![image](https://user-images.githubusercontent.com/24741538/97453588-e636c700-195b-11eb-9d17-0d760450df95.png)
> This has been showing for the past 2 minutes

Yeah, thanks, everything works

**Comment by Scrum** [comment]
hmm, strange now he says that I can but still get 403

**Comment by TheComputerM** [comment]
Are you able to now or should I publish the package?

**Comment by Scrum** [comment]
At the moment I am still getting 403, maybe a little more time is needed, could you post?

**Comment by Scrum** [comment]
yeah, i see permission, if you haven't done it yet, then I can do it

**Comment by Scrum** [comment]
I see that everything worked out for you, thanks anyway

**Comment by TheComputerM** [comment]
@cossssmin What is your npm username, I will also add you as collaborator on npm.

**Comment by cossssmin** [comment]
Same username as here, `cossssmin`
